version: '4.2'
services:
  api-gateway:
    image: api-gateway
    env_file:
      - .env
    networks:
      default:
        aliases:
          - '${API_GATEWAY_URL}'
    ports:
      - '8080:${API_GATEWAY_PORT}'
  user-service:
    image: user-service
    env_file:
      - .env
    networks:
      default:
        aliases:
          - '${USER_SERVICE_URL}'
    ports:
      - '${USER_SERVICE_PORT}:${USER_SERVICE_PORT}'
