version: '4.2'
services:
  #HTTP API Gateway
  api-gateway:
    image: api-gateway
    env_file:
      - ../envs/.env.prod
    networks:
      default:
        aliases:
          - '${API_GATEWAY_URL}'
    ports:
      - '8080:${API_GATEWAY_PORT}'


  # GRPC User Service
  user-service:
    image: user-service
    depends_on:
      - user-service-db
    env_file:
      - ../envs/.env.prod
    networks:
      default:
        aliases:
          - '${USER_SERVICE_URL}'
    ports:
      - '${USER_SERVICE_PORT}:${USER_SERVICE_PORT}'


  # Database for user service
  user-service-db:
    image: postgres:13.3
    container_name: user_service_prod_db
    restart: always
    logging:
      driver: none
    environment:
      POSTGRES_DB: ${USER_SERVICE_DB_NAME}
      POSTGRES_USER: ${USER_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data_prod


  # PGAdmin4
  pgadmin4-container:
    image: dpage/pgadmin4
    depends_on:
      - user-service-db
    restart: always
    logging:
      driver: none
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin_prod

volumes:
  local_pgdata:
  pgadmin-data:

